# Generated by Django 4.2.7 on 2023-12-03 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_course_amount_lesson_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='amount',
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.CharField(blank=True, default=1000, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
